language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: 10
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
branches:
  only:
    - master
